### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by DCGenomics** [MaayanLab/Drugmonizome-ML#3]
When following this lin: https://amp.pharm.mssm.edu/drugmonizome/ off the main README, I get a 502 error.

**Comment by AviMaayan** [comment]
It moved here: https://maayanlab.cloud/drugmonizome we need to fix the redirect.

**Comment by ekropiwnicki** [comment]
fixed the README.

**Comment by u8sand** [comment]
@AviMaayan I updated the amp.pharm => maayanlab.cloud redirect
